services:
  - type: web
    name: backend-doblaweb
    runtime: node
    buildCommand: "cd Backend && npm install"
    startCommand: "cd Backend && npm start"
    root: Backend
    envVars:
      - key: PORT
        value: "10000"